<?php include __DIR__ . '/head.phtml'; ?>

		<div class="row">
			<div class="col-md-12">
				<h1>Welcome, <?php echo $this->me->name; ?>!</h1>

				<h4><a href="/logout">Not you?</a></h4>

				<h3><a href="/print">Print view</a></h3>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				<h2>View Wishlists</h2>

				<?php foreach($this->users as $user): ?>
					<?php if($user['id'] == $this->me->id) continue; ?>
					<a href="/user/<?php echo $user['id']; ?>" class="btn btn-default btn-lg btn-space"><?php echo $user['name']; ?></a>
				<?php endforeach ;?>
			</div>
		</div>

		<div class="row space">
			<div class="col-md-12">
				<h2>Modify Wishlist</h2>

				<div class="table-responsive">
					<table class="table" id="drag">
						<thead>
							<tr>
								<th>Name</th>
								<th>Description</th>
								<th>Price</th>
								<th>Link</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<?php foreach($this->items as $item): ?>
								<tr data-id="<?php echo $item['id']; ?>">
									<td><?php echo $item['name']; ?></td>
									<td><?php echo $item['description']; ?></td>
									<td><?php echo $item['price']; ?></td>
									<td>
										<?php if(!filter_var($item['link'], FILTER_VALIDATE_URL)): ?>
											<?php echo $item['link']; ?>
										<?php else: ?>
											<a href="<?php echo $item['link']; ?>">[ link ]</a>
										<?php endif; ?>
									</td>
									<td><a href="/item/<?php echo $item['id']; ?>">Edit</a></td>
								</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>

				<form class="form-horizontal" role="form" method="POST" action="/item/0">
					<div class="form-group">
						<div class="col-sm-6">
							<input class="form-control" type="text" id="name" name="name" placeholder="Item Name">
						</div>

						<div class="col-sm-6">
							<input class="form-control" type="text" id="description" name="description" placeholder="Item Description">
						</div>
					</div>

					<div class="form-group">
						<div class="col-sm-6">
							<input class="form-control" type="text" id="price" name="price" placeholder="Item Price">
						</div>

						<div class="col-sm-6">
							<input class="form-control" type="text" id="link" name="link" placeholder="Item Link">
						</div>
					</div>

					<div class="form-group">
						<div class="col-xs-12">
							<input type="submit" class="btn btn-default col-xs-12" value="Go!">
						</div>
					</div>
				</form>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				<h2>Purchased Items</h2>

				<div class="table-responsive">
					<table class="table">
						<thead>
							<tr>
								<th>Person</th>
								<th>Name</th>
								<th>Description</th>
								<th>Price</th>
								<th>Link</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<?php foreach($this->purchased as $item): ?>
								<tr>
									<td><?php echo $item->user()->find_one()->name; ?></td>
									<td><?php echo $item->name; ?></td>
									<td><?php echo $item->description; ?></td>
									<td><?php echo $item->price; ?></td>
									<td>
										<?php if(!filter_var($item->link, FILTER_VALIDATE_URL)): ?>
											<?php echo $item->link; ?>
										<?php else: ?>
											<a href="<?php echo $item->link; ?>">[ link ]</a>
										<?php endif; ?>
									</td>
									<td><a href="/user/<?php echo $item->user()->find_one()->id; ?>/<?php echo $item->id; ?>/nope">I didn't purchase this</a></td>
								</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
		</div>

<?php include __DIR__ . '/foot.phtml'; ?>
