<?php include __DIR__ . '/head.phtml'; ?>

		<div class="row">
			<div class="col-md-12">
				<form class="form-horizontal" role="form" method="POST" action="/item/<?php echo $this->item->id; ?>">
					<div class="form-group">
						<label class="col-sm-2 control-label" for="name">Name</label>
						<div class="col-sm-10">
							<input class="form-control" type="text" id="name" name="name" placeholder="Item Name" value="<?php echo htmlspecialchars($this->item->name); ?>">
						</div>
					</div>

					<div class="form-group">
						<label class="col-sm-2 control-label" for="description">Description</label>
						<div class="col-sm-10">
							<input class="form-control" type="text" id="description" name="description" placeholder="Item Description" value="<?php echo htmlspecialchars($this->item->description); ?>">
						</div>
					</div>

					<div class="form-group">
						<label class="col-sm-2 control-label" for="price">Price</label>
						<div class="col-sm-10">
							<input class="form-control" type="text" id="price" name="price" placeholder="Item Price" value="<?php echo htmlspecialchars($this->item->price); ?>">
						</div>
					</div>

					<div class="form-group">
						<label class="col-sm-2 control-label" for="link">Link</label>
						<div class="col-sm-10">
							<input class="form-control" type="text" id="link" name="link" placeholder="Item Link" value="<?php echo htmlspecialchars($this->item->link); ?>">
						</div>
					</div>

					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10 col-xs-12">
							<input type="submit" class="btn btn-default col-xs-12" value="Go!">
						</div>
					</div>
				</form>

				<form class="form-horizontal" role="form" method="POST" action="/item/<?php echo $this->item->id; ?>">
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10 col-xs-12">
							<input type="hidden" name="_method" value="DELETE">
							<input type="submit" class="btn btn-danger col-xs-12" value="Delete">
						</div>
					</div>
			</div>
		</div>

<?php include __DIR__ . '/foot.phtml'; ?>