	</div>

	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
	<script src="https://github.com/isocra/TableDnD/blob/1f8b19584f47eefeadfbe6275bc5fac4bb5c9b92/dist/jquery.tablednd.min.js"></script>

	<script>
	$('#drag').tableDnD({
		onDrop: function(table, row) {
			var rows = $('tbody tr', table);
			var positions = {};

			for(var i = 0; i < rows.length; i++) {
				positions[$(rows[i]).data('id')] = i;
			}

			$.post('/position', {
				positions: positions
			});
		}
	});
	</script>
</body>
</html>
