<?php include __DIR__ . '/head.phtml'; ?>

		<div class="row">
			<div class="col-md-12">
				<h1>Hello <?php echo $this->user->name; ?></h1>

				<form class="form-horizontal" role="form" method="POST" action="/user/auth/<?php echo $this->user->id; ?>">
					<div class="form-group">
						<label class="col-sm-2 control-label" for="pin">Password</label>
						<div class="col-sm-10">
							<input class="form-control" type="password" id="pin" name="pin" placeholder="Password">
						</div>
					</div>

					<input type="hidden" name="form" value="true">

					<div class="form-group">
						<div class="col-sm-10 col-sm-offset-2">
							<input type="submit" class="btn btn-default" value="Go!">
						</div>
					</div>
				</form>
			</div>
		</div>

<?php include __DIR__ . '/foot.phtml'; ?>