<!DOCTYPE html>
<html>
<head>
	<title>Print View | Christmas List</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
	<style>
	th {
		width: 20%;
	}

	.strike {
		text-decoration: line-through;
	}
	</style>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1><?php echo $this->me->name; ?>'s Christmas Shopping List</h1>

				<?php $i = 0; ?>
				<?php foreach($this->users as $user): ?>
					<?php if($user->id == $this->me->id) continue; ?>

					<?php if($i % 2 == 0): ?>
						<div class="row">
					<?php endif; ?>

							<div class="col-md-6 col-xs-6">
								<h2><?php echo $user->name; ?></h2>

								<?php $items = $user->items()->order_by_asc('position')->find_array(); ?>

								<table class="table table-striped table-condensed">
									<thead>
										<tr>
											<th>Name</th>
											<th>Description</th>
											<th>Price</th>
										</tr>
									</thead>
									<tbody>
										<?php foreach($items as $item): ?>
											<tr<?php if($item['purchased'] != 0) echo ' class="strike"'; ?>>
												<td><?php echo $item['name']; ?></td>
												<td><?php echo $item['description']; ?></td>
												<td><?php echo $item['price']; ?></td>
											</tr>
										<?php endforeach; ?>
									</tbody>
								</table>
							</div>

					<?php if($i % 2 != 0): ?>
						</div>
					<?php endif; ?>

					<?php $i++; ?>
				<?php endforeach; ?>
			</div>
		</div>

<?php include __DIR__ . '/foot.phtml'; ?>